version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    environment:
      - ENV=development
    ports:
      - "8000:8000"
    networks:
      - monitoring
    depends_on:
      - prometheus
