global:
  scrape_interval: 5s

scrape_configs:
  # FastAPI metrics
  - job_name: "detoxifyai_app"
    static_configs:
      # - targets: ["100.31.135.60:8000"]  # Change to actual IP like 16.16.193.183:8000
      - targets: ["host.docker.internal:8000"]  # Local FastAPI

  # System metrics
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
